Cryoemio ctf
compSPI/ioSPI pull request #40
Opened 2022-01-28 16:06 UTC by arjunsingh3600

changes to io functions for simSPI to add support for ctf parameters

2022-02-10 01:09 UTC, jedyeo commented
This is ready for review but this is a tricky merge conflict :( @geoffwoollard

2022-02-10 03:18 UTC, ninamiolane commented
The merge conflict is happening because this file is not called cryoemio anymore? Maybe use the correct new name for this file and try again?

Looking good otherwise.

2022-02-10 03:19 UTC, ninamiolane approved these changes
LGTM if conflict gets solved!

2022-02-10 04:59 UTC, geoffwoollard approved these changes
So what's the reason for the merge conflict and what's the plan to resolve?

2022-02-11 00:10 UTC, jedyeo commented
@ninamiolane are we good to merge this?

2022-02-11 16:03 UTC, ninamiolane requested changes
The merge with master has failed, some files with the old version are in there...

2022-02-11 19:01 UTC, jedyeo commented
@ninamiolane i think i fixed it, but don't want to merge without your approval :')

2022-02-11 20:04 UTC, jedyeo commented
@ninamiolane think everything checks out!

2022-02-14 22:32 UTC, ninamiolane requested changes
Thanks for this! A few things to adapt:
- there has been some GitHub issue, as atomic_models.ipynb, save.py, ml_cryo.py should have been removed (as per my review of the codebase)
- please respect the convention decided on ioSPI for the read/write functions

2022-02-14 22:32 UTC, ninamiolane commented on ioSPI/cryo.py
> +def write_defocus_file(defocus_sample, defocus_file):
This should respect the convention for ioSPI (discussed in the PR #46 just merged)

- first argument is where we will write, and it is called "path"
- second argument is what we will write

2022-02-14 22:32 UTC, ninamiolane commented on ioSPI/cryo.py
> +    defocus_dist : list
Adapt docstring

2022-02-14 22:32 UTC, ninamiolane commented on tests/test_atomic_models.py
> +        os.system("wget https://files.rcsb.org/download/" + path)
Nice! 🎉

2022-02-15 18:22 UTC, geoffwoollard commented
We're going ahead with this PR? It has tem simulator specifics in it? The discussion at https://github.com/compSPI/ioSPI/pull/25 suggested that this would be moved to simSPI.

2022-02-16 09:31 UTC, jedyeo commented
> We're going ahead with this PR? It has tem simulator specifics in it? The discussion at #25 suggested that this would be moved to simSPI.

See @thisTyler 's comment at https://github.com/compSPI/ioSPI/pull/25#issuecomment-1040634866

2022-02-16 18:24 UTC, ninamiolane requested changes
I don't understand this PR: 
- it is almost only bringing back files that should be deleted (see previous PRs): is this a GitHub error?
- it is only dealing with imports (..ioSPI): why the change? and that does not match the title of the PR...? Nothing on the CTF?

2022-02-23 00:31 UTC, geoffwoollard commented on tests/test_fourier.py
> +from ..ioSPI import fourier
fourier ins't in ioSPI anymore.

2022-02-23 00:33 UTC, geoffwoollard commented
> I don't understand this PR:
> 
> * it is almost only bringing back files that should be deleted (see previous PRs): is this a GitHub error?
> * it is only dealing with imports (..ioSPI): why the change? and that does not match the title of the PR...? Nothing on the CTF?

Those are all good points @ninamiolane - I am confused too. @jedyeo is Nina right? Or perhaps something was lost in a commit?

Also, `fourier` isn't in` ioSPI `anymore.... this wouldn't pass tests anymore. See https://github.com/compSPI/ioSPI/pull/49

2022-02-23 04:15 UTC, jedyeo commented
@ninamiolane @geoffwoollard after discussing with @arjunsingh3600  it seems that #46 has made this PR redundant (i.e. the refactoring that took place pulled out many of the changes that we made in this branch), but before I'm comfortable with closing this, I want to touch base with @thisTyler early tomorrow and just see that we're all on the same page.

2022-02-23 19:42 UTC, thisTyler commented
Closing this PR as it has been messed up by refactoring quite significantly - we will remake these changes in a fresh branch.

2022-02-23 19:42 UTC, closed without merging