Open datasets
compSPI/ioSPI pull request #8
Opened 2021-06-30 18:36 UTC by NicolasLegendre1

2021-07-02 15:38 UTC, fredericpoitevin commented
Thanks @NicolasLegendre1 for contributing this!

I think we should have "data/input" files in a directory distinct from the code. I'd suggest to move the `.npy` file to `data/` please.

2021-07-02 15:57 UTC, fredericpoitevin requested changes
Pending Nina's approval, I think we can merge as soon as you move the files to `data/` and address the very few comments I made. Thanks @NicolasLegendre1

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    """Open datasets and processes data in ordor to make tensors.
NIT: "in order to"

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    path : string,
What file types are accepted? What does the function expects those files to contain? Please tell us more here.

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    new_size : int.
Please tell us what `size` means.

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +        Images in black and white.
NIT: greyscale images.

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    tensor
If I understand the code correctly, this tensor is specifically a `torch` tensor. Would it be readable by other backends such as `tensorflow` or `numpy`? If not, please mention it here.

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    """Normalize a tensor.
same comment about backend: is this tensor specific to pytorch?

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    """Normalize a tensor.
Idea: if those functions are torch specific, I'd suggest to have the name say it explicitely, e.g.: `normalization_linear_torch()`

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +def normalization_linear(dataset):
How about `normalize(dataset, scale='linear')` ?
That would open the function to maybe have more ways to normalize?

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/dataset.py
> +    path : string,
ditto

2021-07-02 15:57 UTC, fredericpoitevin commented on cryo/test_dataset.py
> +class TestDataset:
Fantastic @NicolasLegendre1 ! :D

2021-07-05 14:47 UTC, ninamiolane requested changes
Very nice!! Just a few thing to adapt.

2021-07-05 14:47 UTC, ninamiolane commented on cryo/dataset.py
> +    dataset : tensor,
NIT: no , at the end here

2021-07-05 14:47 UTC, ninamiolane commented on cryo/dataset.py
> +    dataset : tensor,
(and same thing evrywhere else in the code)

2021-07-05 14:47 UTC, ninamiolane commented on cryo/test_dataset.py
> +class TestDataset:
Agree!! 🎉

2021-07-05 14:50 UTC, ninamiolane commented
I'm not sure that the `.json` files should go to `data/` since they are parameters and not data?

As for the `data_test.npy`, these are not really data, but toy data (just here to run the tests), so they could stay in somewhere in the `tests/` folder?

The real data cannot be stored on GitHub (way too big), thus we will need another public repository to store them and make them available to our users.

2021-07-06 17:00 UTC, fredericpoitevin commented on cryo/test_dataset.py
> +"""Test dataset."""
Right, I missed this. It's important.

I would suggest the following:
```
ioSPI/
L____ iotools/
         L______ atomic_models.py
         L______ cryo_dataset.py.     <==== (currently cryo/dataset.py)
tests/
L____ test_iotools/
         L___________ test_atomic_models.py
         L___________ test_cryo_dataset.py            <==== (currently cryo/test_dataset.py)
         L___________ data_test_cryo_dataset.npy <==== (currently cryo/data_test.npy) 
```

A few notes:
- I haven't homogenized `iospi` ==> `ioSPI` everywhere yet. Should be done asap.
- I think we want `cryo/vae_parameters.json` to go to `data/`

2021-07-06 20:00 UTC, fredericpoitevin commented
> I'm not sure that the `.json` files should go to `data/` since they are parameters and not data?
So we want to have it under `ioSPI/iotools/`?

> As for the `data_test.npy`, these are not really data, but toy data (just here to run the tests), so they could stay in somewhere in the `tests/` folder?
OK makes sense.

> The real data cannot be stored on GitHub (way too big), thus we will need another public repository to store them and make them available to our users.
Agreed.

2021-07-09 21:33 UTC, closed without merging